# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:51+01:00
AUTHOR="romkatv"
DESCRIPTION=""
LICENSE=""
REQUIREMENTS=""
URL="https://github.com/romkatv/zsh-bin"
VERSION=""

zinit \
    as'null' \
    atclone \
    atpull'%atclone' \
    bpick'*.tar.gz' \
    from'gh-r' \
    lucid \
    nocompile \
    nocompletions \
    sbin'bin/zsh*' \
  for @romkatv/zsh-bin

# vim: set ft=zsh et ts=2 sw=2 :
