# zinit package for zsh-static [default]
# Generated by gen-pkg.sh
# 2021-11-26T14:30:05+01:00
AUTHOR=''
DESCRIPTION='Statically-linked, hermetic, relocatable ZSH'
LICENSE=''
MESSAGE=''
PARAM_DEFAULT=''
REQUIREMENTS='cp'
URL='https://github.com/romkatv/zsh-bin'
VERSION='6.1.0'

zinit \
    id-as'romkatv/zsh-bin' \
    as'null' \
    atclone'./install -e yes -d /usr/local' \
    atpull'%atclone' \
    depth'1' \
    git \
    lucid \
    nocompile \
    nocompletions \
  for @romkatv/zsh-bin

# vim: set ft=zsh et ts=2 sw=2 :
