# zinit package for zsh-static [default]
# Generated by gen-pkg.sh
# 2021-11-22T20:01:18+01:00
AUTHOR=""
DESCRIPTION="Statically-linked, hermetic, relocatable ZSH"
LICENSE=""
REQUIREMENTS="cp"
URL="https://github.com/romkatv/zsh-bin"
VERSION=""

zinit \
    as'null' \
    atclone'./install -e yes -d /usr/local' \
    atpull'%atclone' \
    depth'1' \
    git \
    lucid \
    nocompile \
    nocompletions \
  for @romkatv/zsh-bin

# vim: set ft=zsh et ts=2 sw=2 :
