# zinit package for zsh-static [rootless]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T11:44:25+01:00
AUTHOR=''
DESCRIPTION='Statically-linked, hermetic, relocatable ZSH'
LICENSE=''
MESSAGE=''
NAME='zsh-static'
PARAM_DEFAULT=''
REQUIREMENTS='cp'
URL='https://github.com/romkatv/zsh-bin'
VERSION='6.1.0'

zinit \
    as'null' \
    atclone'./install -e no -d ~/.local' \
    atpull'%atclone' \
    depth'1' \
    git \
    id-as'romkatv/zsh-bin' \
    lucid \
    nocompile \
    nocompletions \
  for @romkatv/zsh-bin

# vim: set ft=zsh et ts=2 sw=2 :
