# zinit package for zsh-static [rootless]
# Generated by gen-pkg.sh
# 2021-11-23T15:10:45+01:00
AUTHOR=''
DESCRIPTION='Statically-linked, hermetic, relocatable ZSH'
LICENSE=''
MESSAGE=''
REQUIREMENTS='cp'
URL='https://github.com/romkatv/zsh-bin'
VERSION='6.1.0'

zinit \
    id-as'zsh-static' \
    as'null' \
    atclone'./install -e no -d ~/.local' \
    atpull'%atclone' \
    depth'1' \
    git \
    lucid \
    nocompile \
    nocompletions \
  for @romkatv/zsh-bin

# vim: set ft=zsh et ts=2 sw=2 :
