# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:39+01:00
AUTHOR="zdharma"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zdharma-continuum/zsh-package-any-node"
VERSION="1.0.0"

zinit \
    as'null' \
    atpull'%atclone' \
    git \
    id-as'${${:-%IDAS%}:-%MOD%}' \
    lucid \
    nocompile \
    node'%MOD%;
      %MOD2%;
      %MOD3%;
      %MOD4%;
      %MOD5%;
      %MOD6%;
      %MOD7%;
      %OTHER%' \
    sbin'n:node_modules/.bin/*' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
