# zinit package for any-node [default]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T10:13:42+01:00
AUTHOR='Sebastian Gniazdowski'
DESCRIPTION='Generates table of contents for markdown files inside local git repository. Links are compatible with anchors generated by github or other sites.'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-any-node'
PARAM_DEFAULT='MOD -> lolcatjs'
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/zsh-package-any-node'
VERSION='1.0.0'

zinit \
    as'null' \
    atpull'%atclone' \
    git \
    id-as'${${:-%IDAS%}:-%MOD%}' \
    lucid \
    nocompile \
    node'%MOD%;%MOD2%;%MOD3%;%MOD4%;%MOD5%;%MOD6%;%MOD7%;%OTHER%' \
    sbin'n:node_modules/.bin/*' \
    param'MOD -> lolcatjs' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
