# zinit package for any-node [default]
# Generated by gen-pkg.sh
# 2021-11-23T15:10:18+01:00
AUTHOR='Sebastian Gniazdowski'
DESCRIPTION='Generates table of contents for markdown files inside local git repository. Links are compatible with anchors generated by github or other sites.'
LICENSE='MIT'
MESSAGE=''
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/zsh-package-any-node'
VERSION='1.0.0'

zinit \
    as'null' \
    atpull'%atclone' \
    git \
    id-as'${${:-%IDAS%}:-%MOD%}' \
    lucid \
    nocompile \
    node'%MOD%;
     %MOD2%;
     %MOD3%;
     %MOD4%;
     %MOD5%;
     %MOD6%;
     %MOD7%;
     %OTHER%' \
    sbin'n:node_modules/.bin/*' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
