# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:39+01:00
AUTHOR="zdharma"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zdharma-continuum/zinit-packages"
VERSION="1.0.0"

zinit \
    as'null' \
    atpull'%atclone' \
    gem'%GEM%;
      %GEM2%;
      %GEM3%;
      %GEM4%;
      %GEM5%;
      %GEM6%;
      %GEM7%;
      %OTHER%' \
    git \
    id-as'${${:-%IDAS%}:-%GEM%}' \
    lucid \
    nocompile \
    sbin'g:bin/*' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
