# zinit package for any-gem [default]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T10:13:42+01:00
AUTHOR='Sebastian Gniazdowski'
DESCRIPTION='A package that can install any Ruby Gem and expose its binaries'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-any-gem'
PARAM_DEFAULT='GEM -> lolcat'
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/zinit-packages'
VERSION='1.0.0'

zinit \
    as'null' \
    atpull'%atclone' \
    gem'%GEM%;%GEM2%;%GEM3%;%GEM4%;%GEM5%;%GEM6%;%GEM7%;%OTHER%' \
    git \
    id-as'${${:-%IDAS%}:-%GEM%}' \
    lucid \
    nocompile \
    sbin'g:bin/*' \
    param'GEM -> lolcat' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
