# zinit package for remark [html-only]
# Generated by gen-pkg.sh
# 2021-11-22T20:01:16+01:00
AUTHOR="@unifiedjs collective"
DESCRIPTION="Markdown processor powered by plugins part of the @unifiedjs collective"
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/remarkjs/remark"
VERSION="11.0.2"

zinit \
    as'null' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile \
    node'remark <- !remark-cli;
      remark-html' \
    sbin'n:node_modules/.bin/remark' \
  for @zdharma/null

# vim: set ft=zsh et ts=2 sw=2 :
