# zinit package for remark [html-only]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T10:13:44+01:00
AUTHOR='@unifiedjs collective'
DESCRIPTION='Markdown processor powered by plugins part of the @unifiedjs collective'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-remark'
PARAM_DEFAULT=''
REQUIREMENTS=''
URL='https://github.com/remarkjs/remark'
VERSION='11.0.4'

zinit \
    id-as'zsh-remark' \
    as'null' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile \
    node'remark <- !remark-cli;
      remark-html' \
    sbin'n:node_modules/.bin/remark' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
