# zinit package for system-completions [default]
# Generated by gen-pkg.sh
# 2021-11-26T15:50:50+01:00
AUTHOR='Sebastian Gniazdowski'
DESCRIPTION='A package that brings stock Zsh completions under the control of Zinit'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-system-completions'
PARAM_DEFAULT=''
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/system-completions/'
VERSION='1.0.0'

zinit \
    id-as'zsh-system-completions' \
    as'completion' \
    atclone'print Installing system completions...;
      mkdir -p $ZPFX/funs;
      command cp -f $ZPFX/share/zsh/$ZSH_VERSION/functions/^_* $ZPFX/funs;
      zinit creinstall -q $ZPFX/share/zsh/$ZSH_VERSION/functions;' \
    atload'fpath=( ${(u)fpath[@]:#$ZPFX/share/zsh/*} );
      fpath+=( $ZPFX/funs );' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile \
    run-atpull \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
