# zinit package for github-issues [compact-message]
# Generated by gen-pkg.sh
# 2021-11-23T13:41:54+01:00
AUTHOR="Sebastian Gniazdowski"
DESCRIPTION="Subscribe to projects on Github and receive within shell (under prompt) notifications about new issues."
LICENSE="MIT"
MESSAGE="The profile %PROFILE% has been installed.
To pull the messages the `github-issues-srv' package is also needed."
REQUIREMENTS=""
URL="https://github.com/zdharma-continuum/zsh-github-issues"
VERSION="1.0.0"

zinit \
    atpull'%atclone' \
    git \
    lucid \
    notify'$NOTIFY_MESSAGE' \
    on-update-of'~/.cache/zsh-github-issues/new_titles.log' \
  for @zdharma/zsh-github-issues

# vim: set ft=zsh et ts=2 sw=2 :
