# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:47+01:00
AUTHOR="zdharma"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zdharma/zsh-github-issues"
VERSION="1.0.0"

zinit \
    atpull'%atclone' \
    git \
    lucid \
    notify'New issue: $NOTIFY_MESSAGE' \
    on-update-of'~/.cache/zsh-github-issues/new_titles.log' \
  for @zdharma/zsh-github-issues

# vim: set ft=zsh et ts=2 sw=2 :
