# zinit package for github-issues-srv [default]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T11:44:03+01:00
AUTHOR='Sebastian Gniazdowski'
DESCRIPTION='Subscribe to projects on Github and receive within shell (under prompt) notifications about new issues.'
LICENSE='MIT'
MESSAGE='The profile %PROFILE% has been installed.
To display the messages the `github-issues'\'' package is also needed.'
NAME='zsh-github-issues-srv'
PARAM_DEFAULT=''
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/zsh-github-issues'
VERSION='1.0.1'

zinit \
    atpull'%atclone' \
    git \
    id-as'zdharma-continuum/zsh-github-issues' \
    lucid \
    pick'zsh-github-issues.service.zsh' \
    service'GIT' \
  for @zdharma-continuum/zsh-github-issues

# vim: set ft=zsh et ts=2 sw=2 :
