# zinit package for github-issues-srv [default]
# Generated by gen-pkg.sh
# 2021-11-23T18:05:52+01:00
AUTHOR='Sebastian Gniazdowski'
DESCRIPTION='Subscribe to projects on Github and receive within shell (under prompt) notifications about new issues.'
LICENSE='MIT'
MESSAGE='The profile %PROFILE% has been installed.\nTo display the messages the `github-issues\'' package is also needed.'
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/zsh-github-issues'
VERSION='1.0.1'

zinit \
    id-as'github-issues-srv' \
    atpull'%atclone' \
    git \
    lucid \
    pick'zsh-github-issues.service.zsh' \
    service'GIT' \
  for @zdharma-continuum/zsh-github-issues

# vim: set ft=zsh et ts=2 sw=2 :
