# zinit package for fzf [bgn-binary]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T11:43:51+01:00
AUTHOR='Junegunn Choi'
DESCRIPTION='A command-line fuzzy finder'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-fzf'
PARAM_DEFAULT=''
REQUIREMENTS='cp;bgn'
URL='https://github.com/junegunn/fzf'
VERSION='0.61.1'

zinit \
    atclone'mkdir -p $ZPFX/{bin,man/man1}' \
    atpull'%atclone' \
    dl'https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh -> _fzf_completion;
      https://raw.githubusercontent.com/junegunn/fzf/master/man/man1/fzf-tmux.1 -> $ZPFX/man/man1/fzf-tmux.1;
      https://raw.githubusercontent.com/junegunn/fzf/master/man/man1/fzf.1 -> $ZPFX/man/man1/fzf.1' \
    from'gh-r' \
    id-as'junegunn/fzf' \
    lucid \
    nocompile \
    pick'/dev/null' \
    sbin'fzf' \
  for @junegunn/fzf

# vim: set ft=zsh et ts=2 sw=2 :
