# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:46+01:00
AUTHOR="jhawthorn"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/jhawthorn/fzy"
VERSION=""

zinit \
    as'null' \
    atclone'cp -vf fzy.1 $ZPFX/man/man1' \
    atpull'%atclone' \
    lucid \
    make \
    nocompile \
    sbin'fzy;
      contrib/fzy-*' \
  for @jhawthorn/fzy

# vim: set ft=zsh et ts=2 sw=2 :
