# zinit package for fzy [default]
# Generated by gen-pkg.sh
# 2021-11-22T20:01:13+01:00
AUTHOR="John Hawthorn"
DESCRIPTION="A better fuzzy finder"
LICENSE="MIT"
REQUIREMENTS="cc;make;cp"
URL="https://github.com/jhawthorn/fzy"
VERSION=""

zinit \
    as'null' \
    atclone'cp -vf contrib/fzy-* $ZPFX/bin/' \
    atpull'%atclone' \
    lucid \
    make'PREFIX=$ZPFX install' \
    nocompile \
  for @jhawthorn/fzy

# vim: set ft=zsh et ts=2 sw=2 :
