# zinit package for fzy [default]
# Generated by gen-pkg.sh
# 2021-11-25T12:41:31+01:00
AUTHOR='John Hawthorn'
DESCRIPTION='A better fuzzy finder'
LICENSE='MIT'
MESSAGE=''
REQUIREMENTS='cc;make;cp'
URL='https://github.com/jhawthorn/fzy'
VERSION='1.0.6'

zinit \
    id-as'jhawthorn/fzy' \
    as'null' \
    atclone'cp -vf contrib/fzy-* $ZPFX/bin/' \
    atpull'%atclone' \
    lucid \
    make'PREFIX=$ZPFX install' \
    nocompile \
  for @jhawthorn/fzy

# vim: set ft=zsh et ts=2 sw=2 :
