# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:41+01:00
AUTHOR="zdharma"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/thlorenz/doctoc"
VERSION="1.4.0"

zinit \
    as'null' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile \
    node'!doctoc' \
    sbin'n:node_modules/.bin/doctoc' \
  for @zdharma/null

# vim: set ft=zsh et ts=2 sw=2 :
