# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:49+01:00
AUTHOR="pyenv"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/pyenv/pyenv"
VERSION="1.2.20"

zinit \
    as'command' \
    atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init - > zpyenv.zsh' \
    atinit'export PYENV_ROOT="$PWD' \
    atpull'%atclone' \
    lucid \
    nocompile'!' \
    pick'bin/pyenv' \
    src'zpyenv.zsh' \
  for @pyenv/pyenv

# vim: set ft=zsh et ts=2 sw=2 :
