# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:40+01:00
AUTHOR="zdharma"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/asciidoctor/asciidoctor"
VERSION="2.0.10"

zinit \
    as'null' \
    atpull'%atclone' \
    gem'!asciidoctor' \
    git \
    lucid \
    nocompile \
    sbin'g:bin/asciidoctor' \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
