# zinit package for svn [default]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T11:44:18+01:00
AUTHOR='Yuu Yamashita, Sam Stephenson, Mislav Marohnić, Josh Friend'
DESCRIPTION='Simple Python version management'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-svn'
PARAM_DEFAULT=''
REQUIREMENTS=''
URL='https://github.com/svn/svn'
VERSION='1.2.17'

zinit \
    as'null|monitor' \
    atclone'ziextract --move --auto;
      print -P \\
%F{75}Building Subversion...\\
%f;
      ./configure --prefix='\''$ZPFX'\'' --with-apr='\''$ZPFX'\'' >/dev/null &&
      make >/dev/null &&
      print -P \\
%F{75}Installing Subversion to $ZPFX...\\
%f &&
      make install >/dev/null &&
      print -P \\
%F{34}Installation of Subversion succeeded.%f || print -P \\
%F{160}Installation of Subversion failed.%f' \
    atpull'%atclone' \
    dl'inkhttps://.*/subversion-%VERSION%.tar.bz2' \
    id-as'zsh-svn' \
    is-snippet \
    lucid \
    nocompile'!' \
  for 'https://subversion.apache.org/download.cgi'

# vim: set ft=zsh et ts=2 sw=2 :
