# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:42+01:00
AUTHOR="aws"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/aws/ecs-cli"
VERSION="1.18.1"

zinit \
    as'null' \
    atclone'chmod +x *;
      cp -vf ecs-cli $ZPFX/bin' \
    atpull'%atclone' \
    is-snippet \
    lucid \
    mv'*latest -> ecs-cli' \
    nocompile \
  for @aws/amazon-ecs-cli

# vim: set ft=zsh et ts=2 sw=2 :
