# zinit package for null [default]
# Generated by gen-pkg.sh
# 2021-11-23T15:10:58+01:00
AUTHOR="zdharma-continuum"
DESCRIPTION=""
LICENSE="MIT"
MESSAGE=""
REQUIREMENTS=""
URL="https://github.com/zdharma-continuum/null"
VERSION="$version"

zinit \
    id-as'null' \
    !bash \
    atclone'dostuff;
      echo ok;
      random stuff;
     ' \
    atpull'%atclone' \
    light-mode \
    lucid \
    null \
    run-atpull \
    wait \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
