# zinit package for null [default]
# Generated by gen-pkg.sh
# 2021-11-26T14:30:17+01:00
AUTHOR='zdharma-continuum'
DESCRIPTION=''
LICENSE='MIT'
MESSAGE=''
PARAM_DEFAULT=''
REQUIREMENTS=''
URL='https://github.com/zdharma-continuum/null'
VERSION='$version'

zinit \
    id-as'zinit-package-null' \
    !bash \
    atclone'dostuff;
      echo ok;
      random stuff;' \
    atpull'%atclone' \
    light-mode \
    lucid \
    null \
    run-atpull \
    wait \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
