# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:58+01:00
AUTHOR="zdharma-continuum"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zdharma-continuum/null"
VERSION=""

zinit \
    !bash \
    atclone'dostuff;
      echo ok;
      random stuff;
     ' \
    atpull'%atclone' \
    light-mode \
    lucid \
    null \
    run-atpull \
    wait \
  for @zdharma-continuum/null

# vim: set ft=zsh et ts=2 sw=2 :
