# zinit package for dircolors-material [no-color-swaps]
# Generated by gen-pkg.sh
# 2021-11-22T20:01:08+01:00
AUTHOR="Grigorii Horos"
DESCRIPTION="Dircolors material theme"
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zpm-zsh/material-colors"
VERSION="1.0.3"

zinit \
    atclone'(( !${+commands[dircolors]} )) &&
      local P=g;
      TERM=ansi ${P}dircolors -b material.dircolors >! colors.zsh' \
    atload'zstyle '\'':completion:*:default'\'' list-colors "${(s.:.)LS_COLORS}";
     ' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile'!' \
    pick'colors.zsh' \
  for @zpm-zsh/material-colors

# vim: set ft=zsh et ts=2 sw=2 :
