# Generated by gen-pkg-json.sh
# 2021-11-22T18:35:41+01:00
AUTHOR="zpm-zsh"
DESCRIPTION=""
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zpm-zsh/material-colors"
VERSION="1.0.3"

zinit \
    atclone'(( !${+commands[dircolors]} )) &&
      local P=g;
      TERM=ansi ${P}dircolors -b material.dircolors >! colors.zsh' \
    atload'zstyle :completion:*:default list-colors "${(s.:.)LS_COLORS}";
     ' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile'!' \
    pick'colors.zsh' \
  for @zpm-zsh/material-colors

# vim: set ft=zsh et ts=2 sw=2 :
