# zinit package for dircolors-material [no-zsh-completion]
# Generated by gen-pkg.sh
# 2021-11-22T20:01:08+01:00
AUTHOR="Grigorii Horos"
DESCRIPTION="Dircolors material theme"
LICENSE="MIT"
REQUIREMENTS=""
URL="https://github.com/zpm-zsh/material-colors"
VERSION="1.0.3"

zinit \
    atclone'(( !${+commands[dircolors]} )) &&
      local P=g;
      ${P}sed -i '\''/DIR/c\DIR 38;
     5;
     63;
     1'\'' material.dircolors;
      TERM=ansi ${P}dircolors -b material.dircolors >! colors.zsh' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile'!' \
    pick'colors.zsh' \
    reset \
  for @zpm-zsh/material-colors

# vim: set ft=zsh et ts=2 sw=2 :
