# zinit package for dircolors-material [no-zsh-completion]
# Generated by zinit-pkg-gen.sh
# 2021-11-27T10:13:47+01:00
AUTHOR='Grigorii Horos'
DESCRIPTION='Dircolors material theme'
LICENSE='MIT'
MESSAGE=''
NAME='zsh-dircolors-material'
PARAM_DEFAULT=''
REQUIREMENTS=''
URL='https://github.com/zpm-zsh/material-colors'
VERSION='1.0.0'

zinit \
    id-as'zpm-zsh/material-colors' \
    atclone'(( ! ${+commands[dircolors]} )) &&
      local P=g;
      ${P}sed -i '\''/DIR/c\DIR 38;5;63;1'\'' dircolors/01-base.dircolors &&
      cat dircolors/*.dircolors | TERM=ansi ${P}dircolors -b - >! colors.zsh' \
    atpull'%atclone' \
    git \
    lucid \
    nocompile'!' \
    pick'colors.zsh' \
    reset \
  for @zpm-zsh/material-colors

# vim: set ft=zsh et ts=2 sw=2 :
